### PR TITLE
fix(screenshoter): add correct image paths

### LINKED ISSUE #425: Testreporter missing links
### Description

The issue is in the reporter. When a rendering test is failing you dont get links to the:
baseline and the diff, only to the screenshot taken in the test

### Steps to Reproduce

1. Rendering-test failing
2. Go to reporter

##### Expected behavior

It should show the buttons/links to Screenshot, baseline and diff

##### Actual behavior

Only Screenshot link is visible.

screenshot 2019-02-20 at 13 23 34

### PR DESCRIPTION
**Pull request by stoffeastrom**
Fixes #425

### CODE REVIEW

File: plugins/chai-plugin-screenshot/src/index.js [hunk 1]
```diff
@@ -102,41 +99,41 @@ const plugin = {
...
       );
-      const diffPath = path.resolve(basePath, 'diff', folder, imageName);
-
+      const diff = path.resolve(basePath, 'diff', folder, imageName);
+      const expected = JSON.stringify({
+        baseline,
+        diff,
+        regression,
+      });
+      const actual = {};
```
Comment (cbt1) [inline plugins/chai-plugin-screenshot/src/index.js]: actual is suppose to be an empty object?

Comment (stoffeastrom) [reply plugins/chai-plugin-screenshot/src/index.js]: I just looked at the aw 4 version but we might need some investigation
